### ISSUE TITLE
Metrics client lib has a too generic name (not in hawkular scope)

### ISSUE THREAD

**Issue by simon3z** [hawkular/hawkular-client-ruby#23]
To include the hawkular metrics client at the moment we use:

```
require 'metrics/metrics_client'
```

Since `metrics` is a generic term, I think this should be scoped instead with the `hawkular` name, e.g.:

```
require 'hawkular/metrics_client'
```

cc @pilhuhn @abonas @fryguy

**Comment by Fryguy** [comment]
Yeah, the common pattern for gems is to have (omitting extra folders for brevity) the following.  Note that the file name path generally matches the class being implemented...e.g. lib/hawkular/metrics/nested_class_under_metrics.rb implements Hawkular::Metrics::NestedClassUnderMetrics.

```
hawular-client-ruby
├─ lib
|  ├─ hawkular
|  |  ├─ metrics
|  |  |   └─ nested_class_under_metrics.rb # implements Hawkular::Metrics::NestedClassUnderMetrics
|  |  └─ metrics.rb                        # implements Hawkular::Metrics
|  └─ hawkular.rb                          # implements things directly in Hawkular module
...
```

When a gem is detected, the lib directory is put on the $LOAD_PATH.  So, it's expected that the user will just do `require 'hawkular'` and everything will just work.  Actually, since the gem is named `hawkular-client-ruby` the user might expect `require 'hawkular/client/ruby'` or `require 'hawkular-client-ruby'` to work.  In particular, bundler defaults to the former.  As such, you may want to add dummy files that when required will just subsequently `require 'hawkular'`.

See also http://guides.rubygems.org/make-your-own-gem/#requiring-more-files for some of the layout details and http://guides.rubygems.org/name-your-gem/ for the naming conventions with respect to the gem name and how people might require the gem.

**Comment by simon3z** [comment]
@pilhuhn remember that this probably has repercussion on how we're using this gem for collecting metrics for OpenShift in ManageIQ. Let me know when you update the gem there so we can check if everything is in order.
