### ISSUE TITLE
Use only one websocket for all 'clients'

### ISSUE THREAD

**Issue by pilhuhn** [hawkular/hawkular-client-ruby#42]
We now have websocket support in several places. 
They should all be set up from the credentials passed to the unified client.

Only a single websocket should be setup between Hawkular server and the client gem and should
be (re)used by all the communication.

**Comment by jkremser** [comment]
I've actually done it for operations here https://git.io/vrezU I forgot to close this issue.  

note: The inventory can have also the websocket connection to listen on the inventory events, but this connection can't be shared with the connection for the operations, because there is a different endpoint for it on the Hawkular side. The connections for the inventory events can't be easily shared w/ the current hawkular impl, because part of the endpoint URL is the query (https://git.io/vrezc). That may change, but it'd require to establish some kind of simple protocol on top of WS layer to be able to express what data we want (similarly to the operations@cmdgw)
